import { useEffect, useState } from 'react';
import api from '../utils/api';
import GoalTable from '../components/GoalTable';
import { validateGoalSheet } from '../utils/validation';

const blank = { thrustArea: '', title: '', description: '', uom: 'numeric', scoreType: 'min', target: '', weightage: 10 };
export default function GoalsPage() {
  const [goals, setGoals] = useState([]); const [form, setForm] = useState(blank); const [message, setMessage] = useState('');
  const draftGoals = goals.filter(g => ['draft','rejected'].includes(g.status)); const validation = validateGoalSheet(draftGoals);
  async function load(){ const {data}=await api.get('/goals'); setGoals(data); } useEffect(()=>{load();},[]);
  async function create(e){ e.preventDefault(); setMessage(''); try { await api.post('/goals/draft', form); setForm(blank); await load(); } catch(err){ setMessage(err.response?.data?.message || 'Unable to create goal'); } }
  async function submit(){ setMessage(''); const check = validateGoalSheet(draftGoals); if(check.errors.length){ setMessage(check.errors[0]); return; } try{ const {data}=await api.post('/goals/submit'); setMessage(data.message); await load(); } catch(err){ setMessage(err.response?.data?.message || 'Submission failed'); } }
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold">Goal Creation</h2><p className="text-sm opacity-60">Create up to 8 goals. Total draft/rework weightage must equal exactly 100% before submission.</p></div>{message && <div className="alert alert-info py-2 text-sm">{message}</div>}<form onSubmit={create} className="card border border-base-300 bg-base-100 shadow-sm"><div className="card-body grid gap-3 md:grid-cols-3"><input className="input input-bordered" placeholder="Thrust Area" value={form.thrustArea} onChange={e=>setForm({...form,thrustArea:e.target.value})} required/><input className="input input-bordered" placeholder="Goal Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><input className="input input-bordered" placeholder="Target" value={form.target} onChange={e=>setForm({...form,target:e.target.value})} required/><select className="select select-bordered" value={form.uom} onChange={e=>setForm({...form,uom:e.target.value,scoreType:e.target.value==='timeline'?'timeline':e.target.value==='zero'?'zero':'min'})}><option value="numeric">Numeric</option><option value="percentage">Percentage</option><option value="timeline">Timeline</option><option value="zero">Zero-based</option></select><select className="select select-bordered" value={form.scoreType} onChange={e=>setForm({...form,scoreType:e.target.value})}><option value="min">MIN - higher is better</option><option value="max">MAX - lower is better</option><option value="timeline">Timeline</option><option value="zero">Zero</option></select><input className="input input-bordered" type="number" min="10" placeholder="Weightage" value={form.weightage} onChange={e=>setForm({...form,weightage:e.target.value})} required/><textarea className="textarea textarea-bordered md:col-span-3" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="btn btn-primary md:col-span-1">Add Draft Goal</button></div></form><div className="card border border-base-300 bg-base-100 shadow-sm"><div className="card-body"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">Submission validation</p><p className="text-sm opacity-60">Current total: {validation.total}%</p></div><button className="btn btn-primary" onClick={submit} disabled={validation.errors.length>0}>Submit Goal Sheet</button></div>{validation.errors.length>0 && <ul className="mt-3 list-disc pl-5 text-sm text-error">{validation.errors.map(e=><li key={e}>{e}</li>)}</ul>}</div></div><GoalTable goals={goals}/></div>;
}
